[project]
name = "industrial-fire-detection"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "branca>=0.8.2",
    "click>=8.5.0",
    "folium>=0.20.0",
    "geopandas>=1.1.4",
    "joblib>=1.6.0",
    "numpy>=2.5.2",
    "pandas>=3.0.5",
    "plotly>=7.0.0",
    "pyarrow>=25.0.1",
    "python-dotenv>=1.2.3",
    "pyyaml>=6.0.3",
    "requests>=2.34.2",
    "scikit-learn>=1.9.0",
    "shapely>=2.1.2",
    "streamlit>=1.63.0",
    "streamlit-folium>=0.27.4",
    "tqdm>=4.70.0",
    "xgboost>=3.4.1",
]
