[client]
showErrorDetails = true

[theme]
base = "dark"
primaryColor = "#ff334b"
backgroundColor = "#070a12"
secondaryBackgroundColor = "#0d1321"
textColor = "#f8fafc"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
